class Google_Parameters:
    ##########################################################################################################################################################################################################
    def query_keys():
        query_keys_dict = {
                '': '',
                'main_query': 'as_q=',
                'exact_word': '&as_epq=',
                'any_of_words': '&as_oq=',
                'none_of_words': '&as_eq=',
                'number_from': '&as_nlo=',
                'number_to': '&as_nhi=',
                'site_or_domain': '&as_sitesearch=',
                'results_count': '&num='}
               
        return query_keys_dict
    ##########################################################################################################################################################################################################
    
    
    
    ##########################################################################################################################################################################################################   
    def query_date(start_date='',end_date=''):
        param = f"&tbs=cdr:1,cd_min:{start_date},cd_max:{end_date}"
        return param
    ##########################################################################################################################################################################################################
    
    
    
    ##########################################################################################################################################################################################################
    def search_type():
        search_types_dict = {
            'Open Search':'',
            'Applications': '&tbm=app',
            'Blogs': '&tbm=blg',
            'Books': '&tbm=bks',
            'Discussions': '&tbm=dsc',
            'Images': '&tbm=isch',
            'News': '&tbm=nws',
            'Patents': '&tbm=pts',
            'Places': '&tbm=plcs',
            'Recipes': '&tbm=rcp',
            'Shopping': '&tbm=shop',
            'Video': '&tbm=vid',
            'Scholar' : 'https://scholar.google.com/scholar?' }

        return search_types_dict
    ##########################################################################################################################################################################################################    
    
    
    
    ##########################################################################################################################################################################################################
    def search_type_basic():
        search_types_dict = {
            'Open Search':'',
            'News': '&tbm=nws'
            }
        return search_types_dict    
    ##########################################################################################################################################################################################################
    
    
    
    ##########################################################################################################################################################################################################
    def languages():
        langs_dict = {
                    'Arabic': '&lr=lang_ar',
                    'Armenian': '&lr=lang_hy',
                    'Belarusian': '&lr=lang_be',
                    'Bulgarian': '&lr=lang_bg',
                    'Catalan': '&lr=lang_ca',
                    'Croatian': '&lr=lang_hr',
                    'Czech': '&lr=lang_cs',
                    'Danish': '&lr=lang_da',
                    'Dutch': '&lr=lang_nl',
                    'English': '&lr=lang_en',
                    'Esperanto': '&lr=lang_eo',
                    'Estonian': '&lr=lang_et',
                    'Filipino': '&lr=lang_tl',
                    'Finnish': '&lr=lang_fi',
                    'French': '&lr=lang_fr',
                    'German': '&lr=lang_de',
                    'Greek': '&lr=lang_el',
                    'Hebrew': '&lr=lang_iw',
                    'Hungarian': '&lr=lang_hu',
                    'Icelandic': '&lr=lang_is',
                    'Indonesian': '&lr=lang_id',
                    'Italian': '&lr=lang_it',
                    'Japanese': '&lr=lang_ja',
                    'Korean': '&lr=lang_ko',
                    'Latvian': '&lr=lang_lv',
                    'Lithuanian': '&lr=lang_lt',
                    'Norwegian': '&lr=lang_no',
                    'Persian': '&lr=lang_fa',
                    'Polish': '&lr=lang_pl',
                    'Portuguese': '&lr=lang_pt',
                    'Romanian': '&lr=lang_ro',
                    'Russian': '&lr=lang_ru',
                    'Serbian': '&lr=lang_sr',
                    'Slovak': '&lr=lang_sk',
                    'Slovenian': '&lr=lang_sl',
                    'Spanish': '&lr=lang_es',
                    'Swedish': '&lr=lang_sv',
                    'Thai': '&lr=lang_th',
                    'Turkish': '&lr=lang_tr',
                    'Ukrainian': '&lr=lang_uk',
                    'Vietnamese': '&lr=lang_vi',
                    'Chinese Simplified': '&lr=lang_zh-CN',
                    'Chinese Traditional': '&lr=lang_zh-TW'}       
        
        return langs_dict
    ##########################################################################################################################################################################################################
    
    
    
    ##########################################################################################################################################################################################################
    def interface_langs():
        interface_langs_dict = {
                'English': '&hl=en',
                'Arabic': '&hl=ar',
                'Armenian': '&hl=hy',
                'Belarusian': '&hl=be',
                'Bulgarian': '&hl=bg',
                'Catalan': '&hl=ca',
                'Croatian': '&hl=hr',
                'Czech': '&hl=cs',
                'Danish': '&hl=da',
                'Dutch': '&hl=nl',
                'Esperanto': '&hl=eo',
                'Estonian': '&hl=et',
                'Filipino': '&hl=tl',
                'Finnish': '&hl=fi',
                'French': '&hl=fr',
                'German': '&hl=de',
                'Greek': '&hl=el',
                'Hebrew': '&hl=iw',
                'Hungarian': '&hl=hu',
                'Icelandic': '&hl=is',
                'Indonesian': '&hl=id',
                'Italian': '&hl=it',
                'Japanese': '&hl=ja',
                'Korean': '&hl=ko',
                'Latvian': '&hl=lv',
                'Lithuanian': '&hl=lt',
                'Norwegian': '&hl=no',
                'Persian': '&hl=fa',
                'Polish': '&hl=pl',
                'Portuguese': '&hl=pt',
                'Romanian': '&hl=ro',
                'Russian': '&hl=ru',
                'Serbian': '&hl=sr',
                'Slovak': '&hl=sk',
                'Slovenian': '&hl=sl',
                'Spanish': '&hl=es',
                'Swedish': '&hl=sv',
                'Thai': '&hl=th',
                'Turkish': '&hl=tr',
                'Ukrainian': '&hl=uk',
                'Vietnamese': '&hl=vi',
                'Chinese Simplified': '&hl=zh-CN',
                'Chinese Traditional': '&hl=zh-TW'}
        return interface_langs_dict
    ##########################################################################################################################################################################################################    
        
        
        
    ##########################################################################################################################################################################################################
    def countries():
        countries = {'Country':'',
                    'Afghanistan': '&cr=countryAF',
                    'Albania': '&cr=countryAL',
                    'Algeria': '&cr=countryDZ',
                    'American Samoa': '&cr=countryAS',
                    'Andorra': '&cr=countryAD',
                    'Angola': '&cr=countryAO',
                    'Anguilla': '&cr=countryAI',
                    'Antarctica': '&cr=countryAQ',
                    'Antigua and Barbuda': '&cr=countryAG',
                    'Argentina': '&cr=countryAR',
                    'Armenia': '&cr=countryAM',
                    'Aruba': '&cr=countryAW',
                    'Australia': '&cr=countryAU',
                    'Austria': '&cr=countryAT',
                    'Azerbaijan': '&cr=countryAZ',
                    'Bahamas': '&cr=countryBS',
                    'Bahrain': '&cr=countryBH',
                    'Bangladesh': '&cr=countryBD',
                    'Barbados': '&cr=countryBB',
                    'Belarus': '&cr=countryBY',
                    'Belgium': '&cr=countryBE',
                    'Belize': '&cr=countryBZ',
                    'Benin': '&cr=countryBJ',
                    'Bermuda': '&cr=countryBM',
                    'Bhutan': '&cr=countryBT',
                    'Bolivia': '&cr=countryBO',
                    'Bosnia and Herzegovina': '&cr=countryBA',
                    'Botswana': '&cr=countryBW',
                    'Bouvet Island': '&cr=countryBV',
                    'Brazil': '&cr=countryBR',
                    'British Indian Ocean Territory': '&cr=countryIO',
                    'Brunei Darussalam': '&cr=countryBN',
                    'Bulgaria': '&cr=countryBG',
                    'Burkina Faso': '&cr=countryBF',
                    'Burundi': '&cr=countryBI',
                    'Cambodia': '&cr=countryKH',
                    'Cameroon': '&cr=countryCM',
                    'Canada': '&cr=countryCA',
                    'Cape Verde': '&cr=countryCV',
                    'Cayman Islands': '&cr=countryKY',
                    'Central African Republic': '&cr=countryCF',
                    'Chad': '&cr=countryTD',
                    'Chile': '&cr=countryCL',
                    'China': '&cr=countryCN',
                    'Christmas Island': '&cr=countryCX',
                    'Cocos (Keeling) Islands': '&cr=countryCC',
                    'Colombia': '&cr=countryCO',
                    'Comoros': '&cr=countryKM',
                    'Congo': '&cr=countryCD',
                    'Cook Islands': '&cr=countryCK',
                    'Costa Rica': '&cr=countryCR',
                    "Cote d'Ivoire": '&cr=countryCI',
                    'Croatia': '&cr=countryHR',
                    'Cyprus': '&cr=countryCY',
                    'Czech Republic': '&cr=countryCZ',
                    'Denmark': '&cr=countryDK',
                    'Djibouti': '&cr=countryDJ',
                    'Dominica': '&cr=countryDM',
                    'Dominican Republic': '&cr=countryDO',
                    'East Timor': '&cr=countryTL',
                    'Ecuador': '&cr=countryEC',
                    'Egypt': '&cr=countryEG',
                    'El Salvador': '&cr=countrySV',
                    'Equatorial Guinea': '&cr=countryGQ',
                    'Eritrea': '&cr=countryER',
                    'Estonia': '&cr=countryEE',
                    'Ethiopia': '&cr=countryET',
                    'Falkland Islands (Malvinas)': '&cr=countryFK',
                    'Faroe Islands': '&cr=countryFO',
                    'Fiji': '&cr=countryFJ',
                    'Finland': '&cr=countryFI',
                    'France': '&cr=countryFR',
                    'French Guiana': '&cr=countryGF',
                    'French Polynesia': '&cr=countryPF',
                    'French Southern Territories': '&cr=countryTF',
                    'Gabon': '&cr=countryGA',
                    'Gambia': '&cr=countryGM',
                    'Georgia': '&cr=countryGE',
                    'Germany': '&cr=countryDE',
                    'Ghana': '&cr=countryGH',
                    'Gibraltar': '&cr=countryGI',
                    'Greece': '&cr=countryGR',
                    'Greenland': '&cr=countryGL',
                    'Grenada': '&cr=countryGD',
                    'Guadeloupe': '&cr=countryGP',
                    'Guam': '&cr=countryGU',
                    'Guatemala': '&cr=countryGT',
                    'Guinea': '&cr=countryGN',
                    'Guinea-Bissau': '&cr=countryGW',
                    'Guyana': '&cr=countryGY',
                    'Haiti': '&cr=countryHT',
                    'Heard and McDonald Islands': '&cr=countryHM',
                    'Honduras': '&cr=countryHN',
                    'Hong Kong': '&cr=countryHK',
                    'Hungary': '&cr=countryHU',
                    'Iceland': '&cr=countryIS',
                    'India': '&cr=countryIN',
                    'Indonesia': '&cr=countryID',
                    'Iraq': '&cr=countryIQ',
                    'Ireland': '&cr=countryIE',
                    'Israel': '&cr=countryIL',
                    'Italy': '&cr=countryIT',
                    'Jamaica': '&cr=countryJM',
                    'Japan': '&cr=countryJP',
                    'Jordan': '&cr=countryJO',
                    'Kazakhstan': '&cr=countryKZ',
                    'Kenya': '&cr=countryKE',
                    'Kiribati': '&cr=countryKI',
                    'Kuwait': '&cr=countryKW',
                    'Kyrgyzstan': '&cr=countryKG',
                    "Lao People's Democratic Republic": '&cr=countryLA',
                    'Latvia': '&cr=countryLV',
                    'Lebanon': '&cr=countryLB',
                    'Lesotho': '&cr=countryLS',
                    'Liberia': '&cr=countryLR',
                    'Libya': '&cr=countryLY',
                    'Liechtenstein': '&cr=countryLI',
                    'Lithuania': '&cr=countryLT',
                    'Luxembourg': '&cr=countryLU',
                    'Macau': '&cr=countryMO',
                    'Macedonia': '&cr=countryMK',
                    'Madagascar': '&cr=countryMG',
                    'Malawi': '&cr=countryMW',
                    'Malaysia': '&cr=countryMY',
                    'Maldives': '&cr=countryMV',
                    'Mali': '&cr=countryML',
                    'Malta': '&cr=countryMT',
                    'Marshall Islands': '&cr=countryMH',
                    'Martinique': '&cr=countryMQ',
                    'Mauritania': '&cr=countryMR',
                    'Mauritius': '&cr=countryMU',
                    'Mayotte': '&cr=countryYT',
                    'Mexico': '&cr=countryMX',
                    'Micronesia': '&cr=countryFM',
                    'Moldova': '&cr=countryMD',
                    'Monaco': '&cr=countryMC',
                    'Mongolia': '&cr=countryMN',
                    'Montserrat': '&cr=countryMS',
                    'Morocco': '&cr=countryMA',
                    'Mozambique': '&cr=countryMZ',
                    'Namibia': '&cr=countryNA',
                    'Nauru': '&cr=countryNR',
                    'Nepal': '&cr=countryNP',
                    'Netherlands': '&cr=countryNL',
                    'Netherlands Antilles': '&cr=countryAN',
                    'New Caledonia': '&cr=countryNC',
                    'New Zealand': '&cr=countryNZ',
                    'Nicaragua': '&cr=countryNI',
                    'Niger': '&cr=countryNE',
                    'Nigeria': '&cr=countryNG',
                    'Niue': '&cr=countryNU',
                    'Norfolk Island': '&cr=countryNF',
                    'Northern Maria': '&cr=countryMP',
                    'Norway': '&cr=countryNO',
                    'Oman': '&cr=countryOM',
                    'Pakistan': '&cr=countryPK',
                    'Palau': '&cr=countryPW',
                    'Palestinian Territory': '&cr=countryPS',
                    'Panama': '&cr=countryPA',
                    'Papua New Guinea': '&cr=countryPG',
                    'Paraguay': '&cr=countryPY',
                    'Peru': '&cr=countryPE',
                    'Philippines': '&cr=countryPH',
                    'Pitcairn': '&cr=countryPN',
                    'Poland': '&cr=countryPL',
                    'Portugal': '&cr=countryPT',
                    'Puerto Rico': '&cr=countryPR',
                    'Qatar': '&cr=countryQA',
                    'Reunion': '&cr=countryRE',
                    'Romania': '&cr=countryRO',
                    'Russian Federation': '&cr=countryRU',
                    'Rwanda': '&cr=countryRW',
                    'Saint Kitts and Nevis': '&cr=countryKN',
                    'Saint Lucia': '&cr=countryLC',
                    'Saint Vincent and the Grenadines': '&cr=countryVC',
                    'Samoa': '&cr=countryWS',
                    'San Marino': '&cr=countrySM',
                    'Sao Tome and Principe': '&cr=countryST',
                    'Saudi Arabia': '&cr=countrySA',
                    'Senegal': '&cr=countrySN',
                    'Serbia and Montenegro': '&cr=countryCS',
                    'Seychelles': '&cr=countrySC',
                    'Sierra Leone': '&cr=countrySL',
                    'Singapore': '&cr=countrySG',
                    'Slovakia': '&cr=countrySK',
                    'Slovenia': '&cr=countrySI',
                    'Solomon Islands': '&cr=countrySB',
                    'Somalia': '&cr=countrySO',
                    'South Africa': '&cr=countryZA',
                    'South Georgia and The South Sandwich Islands': '&cr=countryGS',
                    'South Korea': '&cr=countryKR',
                    'Spain': '&cr=countryES',
                    'Sri Lanka': '&cr=countryLK',
                    'St. Helena': '&cr=countrySH',
                    'St. Pierre and Miquelon': '&cr=countryPM',
                    'Suriname': '&cr=countrySR',
                    'Svalbard and Jan Mayen Islands': '&cr=countrySJ',
                    'Swaziland': '&cr=countrySZ',
                    'Sweden': '&cr=countrySE',
                    'Switzerland': '&cr=countryCH',
                    'Taiwan': '&cr=countryTW',
                    'Tajikistan': '&cr=countryTJ',
                    'Tanzania': '&cr=countryTZ',
                    'Thailand': '&cr=countryTH',
                    'Togo': '&cr=countryTG',
                    'Tokelau': '&cr=countryTK',
                    'Tonga': '&cr=countryTO',
                    'Trinidad and Tobago': '&cr=countryTT',
                    'Tunisia': '&cr=countryTN',
                    'Turkey': '&cr=countryTR',
                    'Turkmenistan': '&cr=countryTM',
                    'Turks and Caicos Islands': '&cr=countryTC',
                    'Tuvalu': '&cr=countryTV',
                    'Uganda': '&cr=countryUG',
                    'Ukraine': '&cr=countryUA',
                    'United Arab Emirates': '&cr=countryAE',
                    'United Kingdom': '&cr=countryGB',
                    'United States': '&cr=countryUS',
                    'United States Minor Outlying Islands': '&cr=countryUM',
                    'Uruguay': '&cr=countryUY',
                    'Uzbekistan': '&cr=countryUZ',
                    'Vanuatu': '&cr=countryVU',
                    'Vatican': '&cr=countryVA',
                    'Venezuela': '&cr=countryVE',
                    'Viet Nam': '&cr=countryVN',
                    'Virgin Islands (British)': '&cr=countryVG',
                    'Virgin Islands (U.S.)': '&cr=countryVI',
                    'Wallis and Futuna Islands': '&cr=countryWF',
                    'Western Sahara': '&cr=countryEH',
                    'Yemen': '&cr=countryYE',
                    'Zambia': '&cr=countryZM',
                    'Zimbabwe': '&cr=countryZW'}
        
        return countries
    ##########################################################################################################################################################################################################
    

    
    ########################################################################################################################################################################################################## 
    def term_apperaing():
        term_dict = {
                'Anywhere': '&as_occt=any',
                'In Title': '&as_occt=title',
                'In Text': '&as_occt=body',
                'In URL': '&as_occt=url',
                'In Links': '&as_occt=links'}
        
        return term_dict
    ##########################################################################################################################################################################################################    
    
    
    ########################################################################################################################################################################################################## 
    def file_type():
        types_dict= {'File Type': '',
                    'PDF': '&as_filetype=pdf',
                    'Adobe Postscript': '&as_filetype=ps',
                    'Autodesk': '&as_filetype=dwf',
                    'Google Earth KML': '&as_filetype=kml',
                    'Google Earth KMZ': '&as_filetype=kmz',
                    'Microsoft Excel': '&as_filetype=xls',
                    'Microsoft powerpoint': '&as_filetype=ppt',
                    'Microsoft Word': '&as_filetype=doc',
                    'Rich Text Format': '&as_filetype=rtf',
                    'Shockwave flash': '&as_filetype=swf'}
        return types_dict
    ##########################################################################################################################################################################################################
    
    
    
    ##########################################################################################################################################################################################################
    def countries_acronyms():
        countries = {'Aruba': ['Aruba', 'Aruba'],
                    'Afghanistan': ['Afghanistan', 'Islamic Republic of Afghanistan', 'IRA'],
                    'Angola': ['Angola', 'Republic of Angola'],
                    'Anguilla': ['Anguilla', 'Anguilla'],
                    'Åland Islands': ['Åland Islands', 'Åland Islands'],
                    'Albania': ['Albania', 'Republic of Albania'],
                    'Andorra': ['Andorra', 'Principality of Andorra'],
                    'United Arab Emirates': ['United Arab Emirates','United Arab Emirates','UAE'],
                    'Argentina': ['Argentina', 'Argentine Republic'],
                    'Armenia': ['Armenia', 'Republic of Armenia'],
                    'American Samoa': ['American Samoa', 'American Samoa'],
                    'Antarctica': ['Antarctica', 'Antarctica'],
                    'French Southern Territories': ['French Southern Territories','French Southern Territories','FST'],
                    'Antigua And Barbuda': ['Antigua and Barbuda', 'Antigua and Barbuda'],
                    'Australia': ['Australia', 'Australia'],
                    'Austria': ['Austria', 'Republic of Austria'],
                    'Azerbaijan': ['Azerbaijan', 'Republic of Azerbaijan'],
                    'Burundi': ['Burundi', 'Republic of Burundi'],
                    'Belgium': ['Belgium', 'Kingdom of Belgium'],
                    'Benin': ['Benin', 'Republic of Benin'],
                    'Bonaire, Sint Eustatius And Saba': ['Bonaire, Sint Eustatius and Saba','Bonaire, Sint Eustatius and Saba','BSEAS'],
                    'Burkina Faso': ['Burkina Faso', 'Burkina Faso'],
                    'Bangladesh': ['Bangladesh', "People's Republic of Bangladesh"],
                    'Bulgaria': ['Bulgaria', 'Republic of Bulgaria'],
                    'Bahrain': ['Bahrain', 'Kingdom of Bahrain'],
                    'Bahamas': ['Bahamas', 'Commonwealth of the Bahamas', 'CTB'],
                    'Bosnia And Herzegovina': ['Bosnia and Herzegovina','Republic of Bosnia and Herzegovina','RBAH'],
                    'Saint Barthélemy': ['Saint Barthélemy', 'Saint Barthélemy'],
                    'Belarus': ['Belarus', 'Republic of Belarus'],
                    'Belize': ['Belize', 'Belize'],
                    'Bermuda': ['Bermuda', 'Bermuda'],
                    'Bolivia, Plurinational State Of': ['Bolivia, Plurinational State of','Plurinational State of Bolivia','PSB'],
                    'Brazil': ['Brazil', 'Federative Republic of Brazil', 'FRB'],
                    'Barbados': ['Barbados', 'Barbados'],
                    'Brunei Darussalam': ['Brunei Darussalam', 'Brunei Darussalam'],
                    'Bhutan': ['Bhutan', 'Kingdom of Bhutan'],
                    'Bouvet Island': ['Bouvet Island', 'Bouvet Island'],
                    'Botswana': ['Botswana', 'Republic of Botswana'],
                    'Central African Republic': ['Central African Republic','Central African Republic','CAR'],
                    'Canada': ['Canada', 'Canada'],
                    'Cocos (Keeling) Islands': ['Cocos (Keeling) Islands','Cocos (Keeling) Islands'],
                    'Switzerland': ['Switzerland', 'Swiss Confederation'],
                    'Chile': ['Chile', 'Republic of Chile'],
                    'China': ['China', "People's Republic of China", 'PRC'],
                    "Côte D'Ivoire": ["Côte d'Ivoire", "Republic of Côte d'Ivoire", 'RCD'],
                    'Cameroon': ['Cameroon', 'Republic of Cameroon'],
                    'Congo, The Democratic Republic Of The': ['Congo, The Democratic Republic of thcfte','Congo, The Democratic Republic of the','CTDRT'],
                    'Congo': ['Congo', 'Republic of the Congo', 'RTC'],
                    'Cook Islands': ['Cook Islands', 'Cook Islands'],
                    'Colombia': ['Colombia', 'Republic of Colombia'],
                    'Comoros': ['Comoros', 'Union of the Comoros', 'UTC'],
                    'Cabo Verde': ['Cabo Verde', 'Republic of Cabo Verde', 'RCV'],
                    'Costa Rica': ['Costa Rica', 'Republic of Costa Rica', 'RCR'],
                    'Cuba': ['Cuba', 'Republic of Cuba'],
                    'Curaçao': ['Curaçao', 'Curaçao'],
                    'Christmas Island': ['Christmas Island', 'Christmas Island'],
                    'Cayman Islands': ['Cayman Islands', 'Cayman Islands'],
                    'Cyprus': ['Cyprus', 'Republic of Cyprus'],
                    'Czechia': ['Czechia', 'Czech Republic'],
                    'Germany': ['Germany', 'Federal Republic of Germany', 'FRG'],
                    'Djibouti': ['Djibouti', 'Republic of Djibouti'],
                    'Dominica': ['Dominica', 'Commonwealth of Dominica'],
                    'Denmark': ['Denmark', 'Kingdom of Denmark'],
                    'Dominican Republic': ['Dominican Republic', 'Dominican Republic'],
                    'Algeria': ['Algeria', "People's Democratic Republic of Algeria", 'PDRA'],
                    'Ecuador': ['Ecuador', 'Republic of Ecuador'],
                    'Egypt': ['Egypt', 'Arab Republic of Egypt'],
                    'Eritrea': ['Eritrea', 'the State of Eritrea', 'TSE'],
                    'Western Sahara': ['Western Sahara', 'Western Sahara'],
                    'Spain': ['Spain', 'Kingdom of Spain'],
                    'Estonia': ['Estonia', 'Republic of Estonia'],
                    'Ethiopia': ['Ethiopia', 'Federal Democratic Republic of Ethiopia', 'FDRE'],
                    'Finland': ['Finland', 'Republic of Finland'],
                    'Fiji': ['Fiji', 'Republic of Fiji'],
                    'Falkland Islands (Malvinas)': ['Falkland Islands (Malvinas)',
                    'Falkland Islands (Malvinas)'],
                    'France': ['France', 'French Republic'],
                    'Faroe Islands': ['Faroe Islands', 'Faroe Islands'],
                    'Micronesia, Federated States Of': ['Micronesia, Federated States of','Federated States of Micronesia','FSM'],
                    'Gabon': ['Gabon', 'Gabonese Republic'],
                    'United Kingdom': ['United Kingdom','United Kingdom of Great Britain and Northern Ireland','UKGBANI'],
                    'Georgia': ['Georgia', 'Georgia'],
                    'Guernsey': ['Guernsey', 'Guernsey'],
                    'Ghana': ['Ghana', 'Republic of Ghana'],
                    'Gibraltar': ['Gibraltar', 'Gibraltar'],
                    'Guinea': ['Guinea', 'Republic of Guinea'],
                    'Guadeloupe': ['Guadeloupe', 'Guadeloupe'],
                    'Gambia': ['Gambia', 'Republic of the Gambia', 'RTG'],
                    'Guinea-Bissau': ['Guinea-Bissau', 'Republic of Guinea-Bissau'],
                    'Equatorial Guinea': ['Equatorial Guinea',
                    'Republic of Equatorial Guinea','REG'],
                    'Greece': ['Greece', 'Hellenic Republic'],
                    'Grenada': ['Grenada', 'Grenada'],
                    'Greenland': ['Greenland', 'Greenland'],
                    'Guatemala': ['Guatemala', 'Republic of Guatemala'],
                    'French Guiana': ['French Guiana', 'French Guiana'],
                    'Guam': ['Guam', 'Guam'],
                    'Guyana': ['Guyana', 'Republic of Guyana'],
                    'Hong Kong': ['Hong Kong','Hong Kong Special Administrative Region of China','HKSARC'],
                    'Heard Island And Mcdonald Islands': ['Heard Island and McDonald Islands','Heard Island and McDonald Islands','HIAMI'],
                    'Honduras': ['Honduras', 'Republic of Honduras'],
                    'Croatia': ['Croatia', 'Republic of Croatia'],
                    'Haiti': ['Haiti', 'Republic of Haiti'],
                    'Hungary': ['Hungary', 'Hungary'],
                    'Indonesia': ['Indonesia', 'Republic of Indonesia'],
                    'Isle Of Man': ['Isle of Man', 'Isle of Man'],
                    'India': ['India', 'Republic of India'],
                    'British Indian Ocean Territory': ['British Indian Ocean Territory','British Indian Ocean Territory','BIOT'],
                    'Ireland': ['Ireland', 'Ireland'],
                    'Iran, Islamic Republic Of': ['Iran, Islamic Republic of','Islamic Republic of Iran','IRI'],
                    'Iraq': ['Iraq', 'Republic of Iraq'],
                    'Iceland': ['Iceland', 'Republic of Iceland'],
                    'Israel': ['Israel', 'State of Israel'],
                    'Italy': ['Italy', 'Italian Republic'],
                    'Jamaica': ['Jamaica', 'Jamaica'],
                    'Jersey': ['Jersey', 'Jersey'],
                    'Jordan': ['Jordan', 'Hashemite Kingdom of Jordan'],
                    'Japan': ['Japan', 'Japan'],
                    'Kazakhstan': ['Kazakhstan', 'Republic of Kazakhstan'],
                    'Kenya': ['Kenya', 'Republic of Kenya'],
                    'Kyrgyzstan': ['Kyrgyzstan', 'Kyrgyz Republic'],
                    'Cambodia': ['Cambodia', 'Kingdom of Cambodia'],
                    'Kiribati': ['Kiribati', 'Republic of Kiribati'],
                    'Saint Kitts And Nevis': ['Saint Kitts and Nevis','Saint Kitts and Nevis','SKAN'],
                    'Korea, Republic Of': ['Korea, Republic of', 'Korea, Republic of'],
                    'Kuwait': ['Kuwait', 'State of Kuwait'],
                    "Lao People'S Democratic Republic": ["Lao People's Democratic Republic","Lao People's Democratic Republic",'LPDR'],
                    'Lebanon': ['Lebanon', 'Lebanese Republic'],
                    'Liberia': ['Liberia', 'Republic of Liberia'],
                    'Libya': ['Libya', 'Libya'],
                    'Saint Lucia': ['Saint Lucia', 'Saint Lucia'],
                    'Liechtenstein': ['Liechtenstein', 'Principality of Liechtenstein'],
                    'Sri Lanka': ['Sri Lanka','Democratic Socialist Republic of Sri Lanka','DSRSL'],
                    'Lesotho': ['Lesotho', 'Kingdom of Lesotho'],
                    'Lithuania': ['Lithuania', 'Republic of Lithuania'],
                    'Luxembourg': ['Luxembourg', 'Grand Duchy of Luxembourg', 'GDL'],
                    'Latvia': ['Latvia', 'Republic of Latvia'],
                    'Macao': ['Macao', 'Macao Special Administrative Region of China', 'MSARC'],
                    'Saint Martin (French Part)': ['Saint Martin (French part)','Saint Martin (French part)'],
                    'Morocco': ['Morocco', 'Kingdom of Morocco'],
                    'Monaco': ['Monaco', 'Principality of Monaco'],
                    'Moldova, Republic Of': ['Moldova, Republic of', 'Republic of Moldova'],
                    'Madagascar': ['Madagascar', 'Republic of Madagascar'],
                    'Maldives': ['Maldives', 'Republic of Maldives'],
                    'Mexico': ['Mexico', 'United Mexican States', 'UMS'],
                    'Marshall Islands': ['Marshall Islands','Republic of the Marshall Islands','RTMI'],
                    'North Macedonia': ['North Macedonia', 'Republic of North Macedonia', 'RNM'],
                    'Mali': ['Mali', 'Republic of Mali'],
                    'Malta': ['Malta', 'Republic of Malta'],
                    'Myanmar': ['Myanmar', 'Republic of Myanmar'],
                    'Montenegro': ['Montenegro', 'Montenegro'],
                    'Mongolia': ['Mongolia', 'Mongolia'],
                    'Northern Mariana Islands': ['Northern Mariana Islands','Commonwealth of the Northern Mariana Islands','CTNMI'],
                    'Mozambique': ['Mozambique', 'Republic of Mozambique'],
                    'Mauritania': ['Mauritania', 'Islamic Republic of Mauritania', 'IRM'],
                    'Montserrat': ['Montserrat', 'Montserrat'],
                    'Martinique': ['Martinique', 'Martinique'],
                    'Mauritius': ['Mauritius', 'Republic of Mauritius'],
                    'Malawi': ['Malawi', 'Republic of Malawi'],
                    'Malaysia': ['Malaysia', 'Malaysia'],
                    'Mayotte': ['Mayotte', 'Mayotte'],
                    'Namibia': ['Namibia', 'Republic of Namibia'],
                    'New Caledonia': ['New Caledonia', 'New Caledonia'],
                    'Niger': ['Niger', 'Republic of the Niger', 'RTN'],
                    'Norfolk Island': ['Norfolk Island', 'Norfolk Island'],
                    'Nigeria': ['Nigeria', 'Federal Republic of Nigeria', 'FRN'],
                    'Nicaragua': ['Nicaragua', 'Republic of Nicaragua'],
                    'Niue': ['Niue', 'Niue'],
                    'Netherlands': ['Netherlands', 'Kingdom of the Netherlands', 'KTN'],
                    'Norway': ['Norway', 'Kingdom of Norway'],
                    'Nepal': ['Nepal', 'Federal Democratic Republic of Nepal', 'FDRN'],
                    'Nauru': ['Nauru', 'Republic of Nauru'],
                    'New Zealand': ['New Zealand', 'New Zealand'],
                    'Oman': ['Oman', 'Sultanate of Oman'],
                    'Pakistan': ['Pakistan', 'Islamic Republic of Pakistan', 'IRP'],
                    'Panama': ['Panama', 'Republic of Panama'],
                    'Pitcairn': ['Pitcairn', 'Pitcairn'],
                    'Peru': ['Peru', 'Republic of Peru'],
                    'Philippines': ['Philippines', 'Republic of the Philippines', 'RTP'],
                    'Palau': ['Palau', 'Republic of Palau'],
                    'Papua New Guinea': ['Papua New Guinea','Independent State of Papua New Guinea','ISPNG'],
                    'Poland': ['Poland', 'Republic of Poland'],
                    'Puerto Rico': ['Puerto Rico', 'Puerto Rico'],
                    "Korea, Democratic People'S Republic Of": ["Korea, Democratic People's Republic of","Democratic People's Republic of Korea",'DPRK'],
                    'Portugal': ['Portugal', 'Portuguese Republic'],
                    'Paraguay': ['Paraguay', 'Republic of Paraguay'],
                    'Palestine, State Of': ['Palestine, State of','the State of Palestine','TSP'],
                    'French Polynesia': ['French Polynesia', 'French Polynesia'],
                    'Qatar': ['Qatar', 'State of Qatar'],
                    'Réunion': ['Réunion', 'Réunion'],
                    'Romania': ['Romania', 'Romania'],
                    'Russian Federation': ['Russian Federation', 'Russian Federation'],
                    'Rwanda': ['Rwanda', 'Rwandese Republic'],
                    'Saudi Arabia': ['Saudi Arabia', 'Kingdom of Saudi Arabia', 'KSA'],
                    'Sudan': ['Sudan', 'Republic of the Sudan', 'RTS'],
                    'Senegal': ['Senegal', 'Republic of Senegal'],
                    'Singapore': ['Singapore', 'Republic of Singapore'],
                    'South Georgia And The South Sandwich Islands': ['South Georgia and the South Sandwich Islands','South Georgia and the South Sandwich Islands','SGATSSI'],
                    'Saint Helena, Ascension And Tristan Da Cunha': ['Saint Helena, Ascension and Tristan da Cunha','Saint Helena, Ascension and Tristan da Cunha','SHAATDC'],
                    'Svalbard And Jan Mayen': ['Svalbard and Jan Mayen','Svalbard and Jan Mayen','SAJM'],
                    'Solomon Islands': ['Solomon Islands', 'Solomon Islands'],
                    'Sierra Leone': ['Sierra Leone', 'Republic of Sierra Leone', 'RSL'],
                    'El Salvador': ['El Salvador', 'Republic of El Salvador', 'RES'],
                    'San Marino': ['San Marino', 'Republic of San Marino', 'RSM'],
                    'Somalia': ['Somalia', 'Federal Republic of Somalia', 'FRS'],
                    'Saint Pierre And Miquelon': ['Saint Pierre and Miquelon','Saint Pierre and Miquelon'],
                    'Serbia': ['Serbia', 'Republic of Serbia'],
                    'South Sudan': ['South Sudan', 'Republic of South Sudan'],
                    'Sao Tome And Principe': ['Sao Tome and Principe','Democratic Republic of Sao Tome and Principe','DRSTAP'],
                    'Suriname': ['Suriname', 'Republic of Suriname'],
                    'Slovakia': ['Slovakia', 'Slovak Republic'],
                    'Slovenia': ['Slovenia', 'Republic of Slovenia'],
                    'Sweden': ['Sweden', 'Kingdom of Sweden'],
                    'Eswatini': ['Eswatini', 'Kingdom of Eswatini'],
                    'Sint Maarten (Dutch Part)': ['Sint Maarten (Dutch part)','Sint Maarten (Dutch part)'],
                    'Seychelles': ['Seychelles', 'Republic of Seychelles'],
                    'Syrian Arab Republic': ['Syrian Arab Republic','Syrian Arab Republic'],
                    'Turks And Caicos Islands': ['Turks and Caicos Islands','Turks and Caicos Islands','TACI'],
                    'Chad': ['Chad', 'Republic of Chad'],
                    'Togo': ['Togo', 'Togolese Republic'],
                    'Thailand': ['Thailand', 'Kingdom of Thailand'],
                    'Tajikistan': ['Tajikistan', 'Republic of Tajikistan'],
                    'Tokelau': ['Tokelau', 'Tokelau'],
                    'Turkmenistan': ['Turkmenistan', 'Turkmenistan'],
                    'Timor-Leste': ['Timor-Leste', 'Democratic Republic of Timor-Leste', 'DRT'],
                    'Tonga': ['Tonga', 'Kingdom of Tonga'],
                    'Trinidad And Tobago': ['Trinidad and Tobago',
                    'Republic of Trinidad and Tobago','RTAT'],
                    'Tunisia': ['Tunisia', 'Republic of Tunisia'],
                    'Türkiye': ['Türkiye', 'Republic of Türkiye'],
                    'Tuvalu': ['Tuvalu', 'Tuvalu'],
                    'Taiwan, Province Of China': ['Taiwan, Province of China','Taiwan, Province of China','TPC'],
                    'Tanzania, United Republic Of': ['Tanzania, United Republic of','United Republic of Tanzania','URT'],
                    'Uganda': ['Uganda', 'Republic of Uganda'],
                    'Ukraine': ['Ukraine', 'Ukraine'],
                    'United States Minor Outlying Islands': ['United States Minor Outlying Islands','United States Minor Outlying Islands','USMOI'],
                    'Uruguay': ['Uruguay', 'Eastern Republic of Uruguay', 'ERU'],
                    'United States': ['United States', 'United States of America', 'USA'],
                    'Uzbekistan': ['Uzbekistan', 'Republic of Uzbekistan'],
                    'Holy See (Vatican City State)': ['Holy See (Vatican City State)','Holy See (Vatican City State)'],
                    'Saint Vincent And The Grenadines': ['Saint Vincent and the Grenadines','Saint Vincent and the Grenadines','SVATG'],
                    'Venezuela, Bolivarian Republic Of': ['Venezuela, Bolivarian Republic of','Bolivarian Republic of Venezuela','BRV'],
                    'Virgin Islands, British': ['Virgin Islands, British','British Virgin Islands','BVI'],
                    'Virgin Islands, U.S.': ['Virgin Islands, U.S.','Virgin Islands of the United States','VITUS'],
                    'Viet Nam': ['Viet Nam', 'Socialist Republic of Viet Nam', 'SRVN'],
                    'Vanuatu': ['Vanuatu', 'Republic of Vanuatu'],
                    'Wallis And Futuna': ['Wallis and Futuna', 'Wallis and Futuna', 'WAF'],
                    'Samoa': ['Samoa', 'Independent State of Samoa'],
                    'Yemen': ['Yemen', 'Republic of Yemen'],
                    'South Africa': ['South Africa', 'Republic of South Africa', 'RSA'],
                    'Zambia': ['Zambia', 'Republic of Zambia'],
                    'Zimbabwe': ['Zimbabwe', 'Republic of Zimbabwe']}
        return countries
    ##########################################################################################################################################################################################################
